"""add in user fallowing and fallowers

Revision ID: 33c1739137f5
Revises: c8fd9a3dd9a6
Create Date: 2024-11-13 17:19:45.413913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33c1739137f5"
down_revision: Union[str, None] = "c8fd9a3dd9a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
