"""models

Revision ID: 3d3e7597d644
Revises: 6073330721e1
Create Date: 2024-11-23 12:55:56.005434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3e7597d644'
down_revision: Union[str, None] = '6073330721e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_tweet_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'tweets', ['tweet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_tweet_id_fkey', 'images', 'tweets', ['tweet_id'], ['id'])
    # ### end Alembic commands ###
